# Generated by Django 3.0 on 2019-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('botanical_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('question', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
    ]
